export const tokens = {
  borderRadius: {
    None: 0,
    Sm: 4,
    Md: 8,
    Lg: 16,
    Xl: 24,
    Pill: 500,
    Circular: "50%",
  },
  borderWidth: {
    None: 0,
    Hairline: 1,
    Thin: 2,
    Thick: 4,
    Heavy: 8,
  },
  colorBrand: {
    Darkest: "#003359",
    Dark: "#004980",
    Base: "#0066b2",
    Light: "#b8e1ff",
    Lightest: "#e5f4ff",
  },
  colorNeutral: {
    Darkest: "#2d3338",
    Dark: "#5d6a75",
    Black: "#001322",
    Base: "#b4bbc2",
    Light: "#dfe2e5",
    Lightest: "#f7f7f7",
    White: "#ffffff",
  },
  supportHighLight1: {
    Dark: "#b21b21",
    Base: "#e62229",
    Light: "#ffe5e6",
  },
  supportHighLight2: {
    Dark: "#004980",
    Base: "#0066b2",
    Light: "#e5f4ff",
  },
  supportHighLight3: {
    Dark: "#046104",
    Base: "#068206",
    Light: "#e5ffe5",
  },
  supportHighLight4: {
    Dark: "#873200",
    Base: "#ba4a09",
    Light: "#fbeee7",
  },
  supportHighLight5: {
    Dark: "#bf5b1d",
    Base: "#f3823d",
    Light: "#fff3eb",
  },
  supportHighLight6: {
    Dark: "#cc1f25",
    Base: "#f03c42",
    Light: "#ffe5e6",
  },
  supportHighLight7: {
    Dark: "#ba005d",
    Base: "#f7258e",
    Light: "#fde3f0",
  },
  supportHighLight8: {
    Dark: "#420099",
    Base: "#6622c0",
    Light: "#eee6f8",
  },
  supportHighLight9: {
    Dark: "#006a80",
    Base: "#1fafcc",
    Light: "#e1f7fc",
  },
  supportHighLight10: {
    Dark: "#007367",
    Base: "#1dbfaf",
    Light: "#ddf4f2",
  },
  fontFamily: {
    Ff1: "'Public Sans', sans-serif",
  },
  fontSize: {
    Details: 10,
    Xxxxs: 12,
    Xxxs: 14,
    Xxs: 16,
    Xs: 20,
    Sm: 24,
    Md: 32,
    Lg: 40,
    Xl: 48,
    Xxl: 56,
    Xxxl: 64,
    Xxxxl: 72,
  },
  lineHeight: {
    Superdistant: "200%",
    Distant: "160%",
    Medium: "130%",
    Tight: "100%",
  },
  Spacing: {
    SpacingSuperdistant: 1.5,
    SpacingDistant: 0.5,
    SpacingMedium: 0,
    SpacingTight: -1.5,
  },
  opacity: {
    Semiopaque: "80%",
    Intense: "64%",
    Medium: "32%",
    Light: "16%",
    Semitransparent: "8%",
  },
  shadow: {
    Near: "0px 4px 16px rgba(0, 0, 0, 0.08)",
    Medium: "24px 0 8px rgba(0, 0, 0, 0.08)",
    Distant: "32px 0 16px rgba(0, 0, 0, 0.08)",
    Superdistant: "0 16px 48px rgba(0, 0, 0, 0.08)",
  },
  size: {
    Sm: 16,
    Md: 20,
    Lg: 24,
    Xl: 32,
    Xxl: 48,
  },
  spacingStack: {
    Quark: 4,
    Nano: 8,
    Xxxs: 16,
    Xxs: 24,
    Xs: 32,
    Sm: 40,
    Md: 48,
    Lg: 56,
    Xl: 64,
    Xxl: 80,
    Xxxl: 120,
    Huge: 160,
    Giant: 200,
  },
  spacingInline: {
    Quark: 4,
    Nano: 8,
    Xxxs: 16,
    Xxs: 24,
    Xs: 32,
    Sm: 40,
    Md: 48,
    Lg: 64,
    Xl: 80,
  },
  spacingInsert: {
    Quark: 4,
    Nano: 8,
    Xs: 16,
    Sm: 24,
    Md: 32,
    Lg: 40,
  },
  spaceSquish: {
    Quark: "4px 8",
    Nano: "8px 16",
    Xs: "16px 24",
    Sm: "16px 32",
  },
};

export const buttons = {
  text: {
    default: {
      backgroundColor: "transparent",
      color: tokens.colorBrand.Base,
      hoverColor: tokens.colorNeutral.Lightest,
      hoverTextColor: tokens.colorBrand.Base,
    },
    success: {
      backgroundColor: "transparent",
      color: tokens.supportHighLight3.Base,
      hoverColor: tokens.supportHighLight3.Light,
      hoverTextColor: tokens.supportHighLight3.Base,
    },
    danger: {
      backgroundColor: "transparent",
      color: tokens.supportHighLight1.Base,
      hoverColor: tokens.supportHighLight1.Dark,
      hoverTextColor: tokens.colorNeutral.White,
    },
  },
  contained: {
    default: {
      backgroundColor: tokens.colorBrand.Base,
      hoverColor: tokens.colorBrand.Dark,
      color: tokens.colorNeutral.White,
    },
    success: {
      backgroundColor: tokens.supportHighLight3.Base,
      hoverColor: tokens.supportHighLight3.Dark,
      color: tokens.colorNeutral.White,
    },
    danger: {
      backgroundColor: tokens.supportHighLight1.Base,
      hoverColor: tokens.supportHighLight1.Dark,
      color: tokens.colorNeutral.White,
    },
  },
  outlined: {
    default: {
      backgroundColor: tokens.colorNeutral.White,
      border: `2px solid ${tokens.colorBrand.Base}`,
      color: tokens.colorBrand.Base,
      hoverColor: tokens.colorNeutral.Lightest,
    },
    danger: {
      backgroundColor: tokens.colorNeutral.White,
      border: `2px solid ${tokens.supportHighLight1.Base}`,
      color: tokens.supportHighLight1.Base,
      hoverColor: tokens.colorNeutral.Lightest,
    },
  },
};
